### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by jdmcd** [nodes-vapor/cstack#1]
How can I go about install cstack on Linux? When I run `sudo apt-get install cstack` I get `E: Unable to locate package cstack`. This is really critical for me. Any ideas?

**Comment by jdmcd** [comment]
@steffendsommer Has informed me that this is blocked by a few different things from the main Vapor team, so I will look for an update when the Vapor team is able to publish CStack to APT.

**Comment by joscdk** [comment]
Just to give an update :)

We are during this weekend pushing our new APT repo.

I have informed Nodes, that after the weekend, they should be able to get CStack on the main Vapor APT.

@steffendsommer fyi. I will be at the Nodes CPH office wednesday, if you want me nearby when trying to get it up :)

**Comment by steffendsommer** [comment]
🎉 🎉 🎉  Looking forward to it!

**Comment by jdmcd** [comment]
@joscdk Awesome! I was wondering in the back of my head if this weekend's update was part of the blocker. Can we put a message in this issue (or somewhere else) when the Vapor APT has CStack? That would be greatly appreciated. Thank you!!

**Comment by joscdk** [comment]
@mcdappdev CStack is maintained by Nodes, so would suggest they push it to APT, since they will be able to do proper debugging :)

This weekends update open sources our entire APT, so everyone can look what is going on, and make PR with new/updated packages :) .. Once we have this up, i will work with Nodes to get CStack up during next week, and post an update here :) .. Will be posted in releases on Slack as well :)

**Comment by jdmcd** [comment]
Amazing! Thank you very much. Looking forward to it!

**Comment by joscdk** [comment]
Just to keep you all in the loop, our new APT is up https://github.com/vapor/apt, there is documentation, but of cause need to be a lot more descriptive :D .. I will work together with Nodes wednesday to get CStack on APT :)

**Comment by jdmcd** [comment]
Perfect! Let me know when you get a chance to publish that. Thanks so much!

**Comment by steffendsommer** [comment]
The progress can be followed here: https://github.com/vapor/apt/pull/13

We're close to get it working. SPM seems to have a very limited set of whitelisted flags so you would need to set a flag yourself unfortunately. This is currently not possible if you're using Vapor Cloud - hopefully we will get that feature at some point.

**Comment by jdmcd** [comment]
Got it. What’s the flag? I’m using it on Heroku so what’s the availability there?

**Comment by steffendsommer** [comment]
You'll need to add `-Xlinker --export-dynamic` when running the project (@BrettRToomey). CStack can be installed through apt now so it should be fine on Heroku. Remember to follow the guide from [Vapor's APT repo](https://github.com/vapor/apt) or have a look in our [dockerfiles](https://github.com/nodes-vapor/dockerfiles).

**Comment by jdmcd** [comment]
Perfect will do. Thanks so much!!

**Comment by jdmcd** [comment]
Wait actually on second thought, how would I get it on Heroku? Do I need to write a buildpack?

**Comment by joscdk** [comment]
@mcdappdev you will need to install it manually on Heroku, they don't support APT since you don't have root access, so make a buildpack that installs the packages manually

**Comment by jdmcd** [comment]
That's what I thought. Thank you!

**Comment by jdmcd** [comment]
Looks like this could be of use: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt
